name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      EC2_HOST: "ec2-98-84-183-94.compute-1.amazonaws.com"
      EC2_USER: "ubuntu"
      EC2_APP_PATH: "/home/ubuntu/simple-node-app/"

    steps:
      - name: Checkout Code   # fixed typo
        uses: actions/checkout@v3

      - name: Install Dependencies  # fixed typo
        run: npm install

      - name: SSH into EC2 instance and Deploy  # fixed typos
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          timeout: 60s
          port: 22
          script: |
            set -e
            echo "Pulling latest changes on EC2"
            cd ${{ env.EC2_APP_PATH }}
            git pull origin main
            npm install
            echo "Restarting application"
            pm2 restart app || pm2 start index.js --name app
